name: rustfmt

on: [push]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        submodules: 'recursive'
        fetch-depth: 0 # <-- clone with complete history
        
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - run: |
        cargo fmt --all --manifest-path="./controller/Cargo.toml" && \
        echo ok
    
    - run: |
        cargo fmt --all --manifest-path="./firmware/Cargo.toml" && \
        echo ok
    
    - uses: EndBug/add-and-commit@v10 # You can change this to use a specific version.
      with:
        message: '- cargo fmt'
